# Uncomment the following lines to enable the Corne RGB Underglow
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n
# Keep external power (OLEDs) on even when underglow is toggled off
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n

# Uncomment the following line to enable the Corne OLED Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# nice_oled: Bongo Cat on the left, static image on the right
CONFIG_NICE_OLED_WIDGET_WPM_BONGO_CAT=y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL=n
CONFIG_NICE_OLED_WIDGET_STATIC_IMAGE_PERIPHERAL=y
CONFIG_NICE_OLED_WIDGET_STATIC_IMAGE_PERIPHERAL_MUDGET=y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CUSTOM_X=18
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CUSTOM_Y=0

# allow soft off key 
CONFIG_ZMK_PM_SOFT_OFF=y
